//! File I/O for netlist formats
//!
//! This module provides utilities for reading and writing netlists in various formats.

use crate::netlist::Netlist;
use std::fs::File;
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

/// Error type for I/O operations
#[derive(Debug, thiserror::Error)]
pub enum IoError {
    #[error("File not found: {0}")]
    FileNotFound(String),
    #[error("Invalid file format: {0}")]
    InvalidFormat(String),
    #[error("Parse error at line {line}: {message}")]
    ParseError { line: usize, message: String },
    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
}

/// Result type for I/O operations
pub type IoResult<T> = Result<T, IoError>;

/// Parse a netlist from a file
///
/// This function attempts to auto-detect the file format based on the extension.
///
/// # Supported formats
///
/// - `.net` - ISPD benchmark format
/// - `.v` - Verilog format (limited support)
pub fn read_netlist<P: AsRef<Path>>(path: P) -> IoResult<Netlist> {
    let path = path.as_ref();
    let extension = path
        .extension()
        .and_then(|ext| ext.to_str())
        .ok_or_else(|| IoError::InvalidFormat("No file extension".to_string()))?;

    match extension {
        "net" => read_ispd_format(path),
        "v" => read_verilog_format(path),
        _ => Err(IoError::InvalidFormat(format!(
            "Unsupported file extension: {}",
            extension
        ))),
    }
}

/// Read netlist in ISPD benchmark format
///
/// The ISPD format is a simple text format used in partitioning benchmarks.
fn read_ispd_format<P: AsRef<Path>>(path: P) -> IoResult<Netlist> {
    let file = File::open(path)?;
    let reader = BufReader::new(file);
    let mut netlist = Netlist::new();

    for line in reader.lines() {
        let line = line?;
        let line = line.trim();

        // Skip empty lines and comments
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        // Parse: "NET netname module1 module2 ..."
        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() < 2 || parts[0] != "NET" {
            continue;
        }

        let net_name = parts[1];
        let _ = netlist.add_net(net_name.to_string());

        // Add modules and edges
        for module_name in &parts[2..] {
            if !netlist.modules.contains(&module_name.to_string()) {
                let _ = netlist.add_module(module_name.to_string());
            }
            netlist.add_edge(net_name, module_name).unwrap();
        }
    }

    Ok(netlist)
}

/// Read netlist in Verilog format
///
/// This is a simplified Verilog parser that supports basic module and wire declarations.
fn read_verilog_format<P: AsRef<Path>>(path: P) -> IoResult<Netlist> {
    let file = File::open(path)?;
    let reader = BufReader::new(file);
    let mut netlist = Netlist::new();
    let mut in_module = false;

    for line in reader.lines() {
        let line = line?;
        let line = line.trim();

        // Skip empty lines and comments
        if line.is_empty() || line.starts_with("//") {
            continue;
        }

        // Simplified parsing - real Verilog parsing would be much more complex
        if line.starts_with("module") {
            in_module = true;
        } else if line.starts_with("endmodule") {
            in_module = false;
        } else if in_module && line.starts_with("wire") {
            // Parse: "wire wire_name"
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 2 {
                let _ = netlist.add_net(parts[1].to_string());
            }
        } else if in_module && line.contains("instance") {
            // This is a placeholder - real instance parsing would be more complex
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 2 {
                let module_name = parts[1].trim_end_matches(';');
                if !netlist.modules.contains(&module_name.to_string()) {
                    let _ = netlist.add_module(module_name.to_string());
                }
            }
        }
    }

    Ok(netlist)
}

/// Write a netlist to a file
///
/// This function writes the netlist in a simple text format.
pub fn write_netlist<P: AsRef<Path>>(netlist: &Netlist, path: P) -> IoResult<()> {
    let mut file = File::create(path)?;

    // Write header
    writeln!(file, "# Netlist generated by netlistx-rs")?;
    writeln!(file, "# Modules: {}", netlist.num_modules())?;
    writeln!(file, "# Nets: {}", netlist.num_nets())?;
    writeln!(file)?;

    // Write modules
    writeln!(file, "# Modules")?;
    for module in &netlist.modules {
        writeln!(file, "MODULE {}", module)?;
    }
    writeln!(file)?;

    // Write nets and connections
    writeln!(file, "# Nets")?;
    for net in &netlist.nets {
        let mut modules: Vec<&str> = Vec::new();
        for node in netlist.grph.node_indices() {
            let node_name = &netlist.grph[node];
            if node_name == net {
                for neighbor in netlist.grph.neighbors(node) {
                    let neighbor_name = &netlist.grph[neighbor];
                    if netlist.modules.contains(neighbor_name) {
                        modules.push(neighbor_name);
                    }
                }
            }
        }
        if !modules.is_empty() {
            writeln!(file, "NET {} {}", net, modules.join(" "))?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn test_write_and_read_netlist() {
        let mut netlist = Netlist::new();
        netlist.add_module("m1".to_string()).unwrap();
        netlist.add_module("m2".to_string()).unwrap();
        netlist.add_module("m3".to_string()).unwrap();
        netlist.add_net("n1".to_string()).unwrap();
        netlist.add_net("n2".to_string()).unwrap();
        netlist.add_edge("n1", "m1").unwrap();
        netlist.add_edge("n1", "m2").unwrap();
        netlist.add_edge("n2", "m2").unwrap();
        netlist.add_edge("n2", "m3").unwrap();

        let temp_file = NamedTempFile::new().unwrap();
        write_netlist(&netlist, temp_file.path()).unwrap();

        let temp_path = temp_file.path().with_extension("net");
        std::fs::rename(temp_file.path(), &temp_path).unwrap();

        let read_netlist = read_netlist(&temp_path).unwrap();
        assert_eq!(read_netlist.num_modules(), netlist.num_modules());
        assert_eq!(read_netlist.num_nets(), netlist.num_nets());
    }

    #[test]
    fn test_read_ispd_format() {
        let mut temp_file = NamedTempFile::new().unwrap();
        writeln!(temp_file.as_file_mut(), "# Test netlist").unwrap();
        writeln!(temp_file.as_file_mut(), "NET net1 m1 m2 m3").unwrap();
        writeln!(temp_file.as_file_mut(), "NET net2 m2 m4").unwrap();

        let netlist = read_ispd_format(temp_file.path()).unwrap();
        assert_eq!(netlist.num_nets(), 2);
        assert_eq!(netlist.num_modules(), 4);
    }

    #[test]
    fn test_read_invalid_format() {
        let temp_file = NamedTempFile::new().unwrap();
        let temp_path = temp_file.path().with_extension("invalid");
        std::fs::rename(temp_file.path(), &temp_path).unwrap();

        let result = read_netlist(&temp_path);
        assert!(result.is_err());
    }
}
